---
RecipeFormatVersion: '2020-01-25'
ComponentName: aws.greengrass.crypto.Pkcs11Provider
ComponentDescription: AWS Greengrass Pkcs11 Provider
ComponentPublisher: AWS
ComponentVersion: '0.0.0'
ComponentType: 'aws.greengrass.plugin'
ComponentConfiguration:
  DefaultConfiguration:
    name: ''
    library: ''
    slot: 0
    userPin: ''
Manifests:
  - Artifacts:
      - URI: s3://gg-dev-artifacts-$stage/$componentName/$version/aws.greengrass.crypto.Pkcs11Provider.jar